### ISSUE TITLE
User which is not admin cannot insert image into post

### ISSUE THREAD

**Issue by DerKnecht** [dcooney/instant-images#6]
I really love your plugin.

But I encounter an issue.
To reproduce:
1. I login as an user which is NOT an admin. (Role is Editor)
2. I edit a post. (It's my own)
3. Then I try to insert an image via Instant Images.
4. Here the error occurs: "Unable to download image to server, please check your server permissions."

It works if I use an user which has the admin role.
Maybe there's a fix or I missed something?

**Comment by dcooney** [comment]
Hmm interesting. Are you using Gutenberg or the classic editor?

Maybe have a look at this filter.
https://connekthq.com/plugins/instant-images/#6

**Comment by DerKnecht** [comment]
This is still happening in Firefox 66.0.2. I use the classic editor and I had a look at the link you posted but it didn't give a solution to the problem.

**Comment by dcooney** [comment]
Closed this due to inactivity without fully re-reading the issue. Re-opened.

**Comment by kelna** [comment]
I get the same error message ("check your file permissions...") with both admin and editor accounts in Brave and Chrome.

**Comment by lauragobrightly** [comment]
I am also experiencing this issue when using Gutenberg. Only users with administrator access are able to upload images through the Gutenberg block. I get errors in the console related to "server permissions" but this seems unlikely because server permissions are fine when using admin role? 

Screen recording: https://drive.google.com/file/d/1C_qqF40VMAuisZK6nPzjjnoapMJgpnrl/view

**Comment by dcooney** [comment]
4.2.0 updates Instant Images permissions to use upload_images. Instant Images is not only shown in Gutenberg for users who have that role assigned.
